# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83eb9ad685dc738173236a3d0a865012db3f977935dd78de559a2a1bfd89ebc751275adc9e2aeaa5e941080047b11340f66d1bb851bd8a5ca056bb6e64567bd6

test:
  secret_key_base: 06ab04e00904dbd3c45076f4a47963759492103d9c8cf622854335d2bb8deb218224843565e0fce7c3d9e9a95cd8a74d1c96626a380512e58effdb3f63a01d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
